# Generated by Django 4.2.27 on 2026-04-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_analysis', '0011_namespace_nats_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceapimodel',
            name='field_schema',
            field=models.JSONField(blank=True, default=list, help_text='接口返回字段定义（数据源级配置，表格默认列可使用）'),
        ),
    ]
