from apps.cmdb.collection.collect_plugin.qcloud import QCloudCollectMetrics
from apps.cmdb.collection.plugins.base import AutoRegisterCollectionPluginMixin, bind_collection_mapping
from apps.cmdb.constants.constants import CollectPluginTypes


class QCloudCollectionPlugin(AutoRegisterCollectionPluginMixin, QCloudCollectMetrics):
    supported_task_type = CollectPluginTypes.CLOUD
    supported_model_id = "qcloud"
    plugin_source = "community"
    priority = 10

    metric_names = [
        "qcloud_bucket_info_gauge",
        "qcloud_clb_info_gauge",
        "qcloud_cmq_info_gauge",
        "qcloud_cmq_topic_info_gauge",
        "qcloud_cvm_info_gauge",
        "qcloud_domain_info_gauge",
        "qcloud_eip_info_gauge",
        "qcloud_filesystem_info_gauge",
        "qcloud_mongodb_info_gauge",
        "qcloud_mysql_info_gauge",
        "qcloud_pgsql_info_gauge",
        "qcloud_pulsar_cluster_info_gauge",
        "qcloud_redis_info_gauge",
        "qcloud_rocketmq_info_gauge",
    ]

    field_mappings = {
        "qcloud_bucket": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "region": "region",
        },
        "qcloud_clb": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "tag": "tag",
            "project_id": "project_id",
            "security_group_id": "security_group_id",
            "vpc": "vpc",
            "region": "region",
            "master_zone": "master_zone",
            "backup_zone": "backup_zone",
            "status": "status",
            "domain": "domain",
            "ip_addr": "ip_addr",
            "type": "type",
            "isp": "isp",
            "charge_type": "charge_type",
        },
        "qcloud_cmq": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "tag": "tag",
            "region": "region",
            "status": "status",
            "max_delay_s": "max_delay_s",
            "polling_wait_s": "polling_wait_s",
            "visibility_timeout_s": "visibility_timeout_s",
            "max_message_b": "max_message_b",
            "qps": "qps",
        },
        "qcloud_cmq_topic": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "tag": "tag",
            "region": "region",
            "status": "status",
            "max_retention_s": "max_retention_s",
            "max_message_b": "max_message_b",
            "filter_type": "filter_type",
            "qps": "qps",
        },
        "qcloud_cvm": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "ip_addr": "ip_addr",
            "public_ip": "public_ip",
            "region": "region",
            "zone": "zone",
            "vpc": "vpc",
            "status": "status",
            "instance_type": "instance_type",
            "os_name": "os_name",
            "vcpus": (int, "vcpus"),
            "memory_mb": (int, "memory_mb"),
            "charge_type": "charge_type",
        },
        "qcloud_domain": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "tld": "tld",
            "status": "status",
        },
        "qcloud_eip": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "tag": "tag",
            "region": "region",
            "status": "status",
            "type": "type",
            "ip_addr": "ip_addr",
            "instance_type": "instance_type",
            "instance_id": "instance_id",
            "isp": "isp",
            "charge_type": "charge_type",
        },
        "qcloud_filesystem": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "tag": "tag",
            "region": "region",
            "zone": "zone",
            "status": "status",
            "protocol": "protocol",
            "type": "type",
            "net_limit": (int, "net_limit"),
            "size_gib": (int, "size_gib"),
        },
        "qcloud_mongodb": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "ip_addr": "ip_addr",
            "tag": "tag",
            "project_id": "project_id",
            "vpc": "vpc",
            "region": "region",
            "zone": "zone",
            "port": "port",
            "status": "status",
            "cluster_type": "cluster_type",
            "machine_type": "machine_type",
            "version": "version",
            "cpu": "cpu",
            "memory_mb": "memory_mb",
            "volume_mb": "volume_mb",
            "secondary_num": "secondary_num",
            "mongos_cpu": "mongos_cpu",
            "mongos_memory_mb": "mongos_memory_mb",
            "mongos_node_num": "mongos_node_num",
            "charge_type": "charge_type",
        },
        "qcloud_mysql": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "ip_addr": "ip_addr",
            "region": "region",
            "zone": "zone",
            "status": "status",
            "volume": (int, "volume"),
            "memory_mb": (int, "memory_mb"),
            "charge_type": "charge_type",
        },
        "qcloud_pgsql": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "tag": "tag",
            "project_id": "project_id",
            "vpc": "vpc",
            "region": "region",
            "zone": "zone",
            "status": "status",
            "chartset": "chartset",
            "engine": "engine",
            "mode": "mode",
            "version": "version",
            "kernel_version": "kernel_version",
            "cpu": "cpu",
            "memory_mb": "memory_mb",
            "volume_mb": "volume_mb",
            "charge_type": "charge_type",
        },
        "qcloud_pulsar_cluster": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "tag": "tag",
            "project_id": "project_id",
            "region": "region",
            "status": "status",
            "version": "version",
            "vpc_endpoint": "vpc_endpoint",
            "public_endpoint": "public_endpoint",
            "max_namespace_num": "max_namespace_num",
            "max_topic_num": "max_topic_num",
            "max_qps": "max_qps",
            "max_retention_s": "max_retention_s",
            "max_storage_mb": "max_storage_mb",
            "max_delay_s": "max_delay_s",
            "charge_type": "charge_type",
        },
        "qcloud_redis": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "ip_addr": "ip_addr",
            "vpc": "vpc",
            "region": "region",
            "zone": "zone",
            "port": "port",
            "wan_address": "wan_address",
            "status": "status",
            "sub_status": "sub_status",
            "engine": "engine",
            "version": "version",
            "type": "type",
            "memory_mb": "memory_mb",
            "shard_size": "shard_size",
            "shard_num": "shard_num",
            "replicas_num": "replicas_num",
            "client_limit": "client_limit",
            "net_limit": "net_limit",
            "charge_type": "charge_type",
        },
        "qcloud_rocketmq": {
            "inst_name": QCloudCollectMetrics.set_instance_inst_name,
            "assos": QCloudCollectMetrics.set_asso_instances,
            "resource_name": "resource_name",
            "resource_id": "resource_id",
            "region": "region",
            "zone": "zone",
            "status": "status",
            "topic_num": (int, "topic_num"),
            "used_topic_num": (int, "used_topic_num"),
            "tpsper_name_space": (int, "tpsper_name_space"),
            "name_space_num": (int, "name_space_num"),
            "group_num": (int, "group_num"),
        },
    }

    @property
    def _metrics(self):
        return list(self.metric_names)

    @property
    def model_field_mapping(self):
        return {
            model_id: bind_collection_mapping(self, mapping)
            for model_id, mapping in self.field_mappings.items()
        }