port: 4222
monitor_port: 8222
trace: false
debug: false
logtime: false

jetstream: enabled
jetstream {
  store_dir=/nats/storage
  domain=bklite
}

server_name=nats-server
authorization {
  default_permissions = {
    publish = []
    subscribe = []
  }
  users = [
    {
      user: "admin"
      password: "bklite-password"
      permissions: {
        publish = [">"]
        subscribe = [">"]
      }
    }
  ]
}
