# Generated by Django 4.2.22 on 2026-02-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0009_remove_correlationrules_aggregation_rules_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="alert",
            name="alert_created_btree",
        ),
        migrations.RemoveIndex(
            model_name="alert",
            name="alert_operator_gin",
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="event_labels_gin",
        ),
        migrations.RemoveIndex(
            model_name="incident",
            name="incident_created_btree",
        ),
        migrations.RemoveIndex(
            model_name="incident",
            name="incident_operator_gin",
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["operator"], name="alert_operator_gin"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["labels"], name="event_labels_gin"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["operator"], name="incident_operator_gin"),
        ),
    ]
