# Generated by Django 4.2.7 on 2026-04-02 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0011_alarmstrategy_last_execute_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event", name="push_source_id", field=models.CharField(default="default", help_text="事件推送来源", max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="source",
            field=models.ForeignKey(help_text="通道", on_delete=django.db.models.deletion.CASCADE, to="alerts.alertsource"),
        ),
    ]
