"""Redis 运维工具模块

这个模块提供 Redis 相关的内置工具集，包含字符串、哈希、列表、集合、有序集合、流、JSON、查询引擎和服务管理等能力。
"""

from apps.opspilot.metis.llm.tools.redis.hash import (
    redis_get_vector_from_hash,
    redis_hdel,
    redis_hexists,
    redis_hget,
    redis_hgetall,
    redis_hkeys,
    redis_hlen,
    redis_hset,
    redis_hvals,
    redis_set_vector_in_hash,
)
from apps.opspilot.metis.llm.tools.redis.json import redis_json_arrappend, redis_json_del, redis_json_get, redis_json_objkeys, redis_json_set
from apps.opspilot.metis.llm.tools.redis.list import redis_lindex, redis_llen, redis_lpop, redis_lpush, redis_lrange, redis_rpop, redis_rpush
from apps.opspilot.metis.llm.tools.redis.pub_sub import redis_publish, redis_pubsub_channels, redis_subscribe, redis_unsubscribe
from apps.opspilot.metis.llm.tools.redis.query_engine import (
    redis_create_vector_index_hash,
    redis_get_index_info,
    redis_get_indexed_keys_number,
    redis_get_indexes,
    redis_hybrid_search,
    redis_vector_search_hash,
)
from apps.opspilot.metis.llm.tools.redis.server_management import (
    redis_client_list,
    redis_dbsize,
    redis_delete,
    redis_exists,
    redis_expire,
    redis_flushdb,
    redis_get_key_summary,
    redis_get_key_value,
    redis_info,
    redis_key_type,
    redis_ping,
    redis_rename,
    redis_scan_keys,
    redis_ttl,
)
from apps.opspilot.metis.llm.tools.redis.set import (
    redis_sadd,
    redis_scard,
    redis_sdiff,
    redis_sinter,
    redis_sismember,
    redis_smembers,
    redis_srem,
    redis_sunion,
)
from apps.opspilot.metis.llm.tools.redis.sorted_set import (
    redis_zadd,
    redis_zcard,
    redis_zrange,
    redis_zrangebyscore,
    redis_zrank,
    redis_zrem,
    redis_zrevrange,
    redis_zscore,
)
from apps.opspilot.metis.llm.tools.redis.stream import (
    redis_xack,
    redis_xadd,
    redis_xdel,
    redis_xgroup_create,
    redis_xrange,
    redis_xread,
    redis_xreadgroup,
    redis_xrevrange,
)
from apps.opspilot.metis.llm.tools.redis.string import redis_append, redis_get, redis_getdel, redis_mget, redis_set, redis_strlen

CONSTRUCTOR_PARAMS = [
    {"name": "redis_instances", "type": "string", "required": False, "description": "Redis多实例JSON配置"},
    {"name": "redis_default_instance_id", "type": "string", "required": False, "description": "默认Redis实例ID"},
]

__all__ = [
    "CONSTRUCTOR_PARAMS",
    "redis_ping",
    "redis_dbsize",
    "redis_info",
    "redis_client_list",
    "redis_scan_keys",
    "redis_key_type",
    "redis_exists",
    "redis_expire",
    "redis_ttl",
    "redis_delete",
    "redis_rename",
    "redis_get_key_value",
    "redis_get_key_summary",
    "redis_flushdb",
    "redis_set",
    "redis_get",
    "redis_mget",
    "redis_append",
    "redis_strlen",
    "redis_getdel",
    "redis_hset",
    "redis_hget",
    "redis_hdel",
    "redis_hgetall",
    "redis_hexists",
    "redis_hkeys",
    "redis_hvals",
    "redis_hlen",
    "redis_set_vector_in_hash",
    "redis_get_vector_from_hash",
    "redis_lpush",
    "redis_rpush",
    "redis_lpop",
    "redis_rpop",
    "redis_lrange",
    "redis_llen",
    "redis_lindex",
    "redis_sadd",
    "redis_srem",
    "redis_smembers",
    "redis_sismember",
    "redis_scard",
    "redis_sinter",
    "redis_sunion",
    "redis_sdiff",
    "redis_zadd",
    "redis_zrange",
    "redis_zrem",
    "redis_zscore",
    "redis_zcard",
    "redis_zrevrange",
    "redis_zrangebyscore",
    "redis_zrank",
    "redis_xadd",
    "redis_xread",
    "redis_xrange",
    "redis_xrevrange",
    "redis_xdel",
    "redis_xgroup_create",
    "redis_xreadgroup",
    "redis_xack",
    "redis_publish",
    "redis_pubsub_channels",
    "redis_subscribe",
    "redis_unsubscribe",
    "redis_json_set",
    "redis_json_get",
    "redis_json_del",
    "redis_json_arrappend",
    "redis_json_objkeys",
    "redis_get_indexes",
    "redis_get_index_info",
    "redis_get_indexed_keys_number",
    "redis_create_vector_index_hash",
    "redis_vector_search_hash",
    "redis_hybrid_search",
]
