# Generated by Django 4.2.27 on 2026-04-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0030_custom_api_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorobject',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='监控对象显示名称'),
        ),
        migrations.AddField(
            model_name='monitorobject',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='是否可见'),
        ),
        migrations.AddField(
            model_name='monitorobjecttype',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='分类名称'),
        ),
    ]
