// AUTO-GENERATED by web/scripts/generate-capability-matrix.ts — DO NOT EDIT BY HAND.
// Source of truth: server/apps/monitor/support-files/plugins/Telegraf/snmp/<object>_<brand>/metrics.json
// Regenerate: pnpm gen:capability-matrix

import type { CapabilityMatrix } from './capability-matrix-core';

export const CAPABILITY_MATRIX: CapabilityMatrix = {
  "switch": [
    {
      "collectType": "snmp",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_3com",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_advantech",
      "capabilities": [
        "uptime",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_alaxala",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_alcatel",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_alliedtelesis",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_allnet",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_antaira",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_apresia",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_arista",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_aruba",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_asterfusion",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_atop",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_avaya_ers",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_bdcom",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_brocade",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cambium_switch",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cern_wrs",
      "capabilities": [
        "uptime",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cisco",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cisco_nexus",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ciscosb",
      "capabilities": [
        "uptime",
        "cpu",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_comtrol",
      "capabilities": [
        "uptime",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cumulus",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_dasan",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_datacom",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_datacom_dmswitch",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_dcn",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_dellforce",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_dellos10",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_dlink",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_edgecore",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_eltex",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_enterasys",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_etherwan",
      "capabilities": [
        "uptime",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_exalink",
      "capabilities": [
        "uptime",
        "memory",
        "temperature",
        "fan",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_extreme",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_extreme_vdx",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_fiberhome",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_fortiswitch",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_fs",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_futurematrix",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_garretcom",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_gcom",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_h3c",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_hirschmann",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_hirschmann_hios",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_hphpn",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_huawei",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_inhand",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_intelbras",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ipinfusion",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_juniper",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_korenix",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_kyland",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_lancom",
      "capabilities": [
        "uptime",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_lantech",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_lenovocnos",
      "capabilities": [
        "uptime",
        "cpu",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_linksys",
      "capabilities": [
        "uptime",
        "cpu",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_maipu",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_mellanox",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_microsens",
      "capabilities": [
        "uptime",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_mikrotik",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_moxa",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_moxa_edsg",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_murrelektronik",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_netgear",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_netonix",
      "capabilities": [
        "uptime",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_nexans",
      "capabilities": [
        "uptime",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_nokia",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_omniswitch",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_omnitron",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_parks",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_pbn",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_phoenixcontact",
      "capabilities": [
        "uptime",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_pica8",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_planet",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_pluribus",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_positron",
      "capabilities": [
        "uptime",
        "cpu",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_qtech",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_quanta",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_raisecom_switch",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_redlion",
      "capabilities": [
        "uptime",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_robustel_switch",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_rubytech",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ruggedcom",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ruijie",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_scalance",
      "capabilities": [
        "uptime",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_sixnet",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_smartbyte",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_snr",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_tailyn",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_telco",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_tplink",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_transition",
      "capabilities": [
        "uptime",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_tsntec",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ubiquiti",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ubiquoss",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_voss",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_wago",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_waystream",
      "capabilities": [
        "uptime",
        "temperature",
        "fan",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_weidmuller",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_westermo",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_witek",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_womaster",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_xikestor",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_yamaha",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_zte",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_zyxel",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    }
  ],
  "router": [
    {
      "collectType": "snmp",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_6wind",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_adtran",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_advantech_router",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_aethra",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_avaya",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_avici",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_benu",
      "capabilities": [
        "uptime",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_bintec",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cisco_iosxr",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cisco_router",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cloudgenix",
      "capabilities": [
        "uptime",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cradlepoint",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_digi",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_digi_transport",
      "capabilities": [
        "uptime",
        "cpu",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_draytek",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_edgerouter",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ericsson_router",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_firebrick",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ge_mds",
      "capabilities": [
        "uptime",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_harbour",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_huawei_ar",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_huawei_atn",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_huawei_ne",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_inhand_router",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_juniper_mx",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_lancom",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_mikrotik_router",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_milesight",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_multitech",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_nec",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_netelastic",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_netmodule",
      "capabilities": [
        "uptime",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_nokia_router",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_oneaccess",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_peplink",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_racom_ripex",
      "capabilities": [
        "uptime",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_robustel",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_sierrawireless",
      "capabilities": [
        "uptime",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_teldat",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_teltonika",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_unisphere",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_velocloud",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_versa",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_viprinet",
      "capabilities": [
        "uptime",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_viptela",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_vyatta",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_yamaha_router",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    }
  ],
  "firewall": [
    {
      "collectType": "snmp",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_amaranten",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_barracuda",
      "capabilities": [
        "uptime",
        "temperature",
        "fan",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_barracuda_cloudgen",
      "capabilities": [
        "uptime",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_blockbit",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_bluedon",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_checkpoint",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_cisco_esa",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cisco_firewall",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_cisco_wsa",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_clavister",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_dptech",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_fireeye",
      "capabilities": [
        "uptime",
        "cpu",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_forcepoint",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_fortimail",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_fortinet",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_fortiweb",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_genua",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_h3c_firewall",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_hillstone",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_huawei_usg",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_ipfire",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_juniper_firewall",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_kerio",
      "capabilities": [
        "uptime",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_mguard",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_neteye",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_opnsense",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_paloalto",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_pfsense",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_pulsesecure",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_sangfor",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_screenos",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_securepoint",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_secworld",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_sonicwall",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_sophos",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_stormshield",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_topsec",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_watchguard",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_westone",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_zorp",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_zyxel_firewall",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    }
  ],
  "loadbalance": [
    {
      "collectType": "snmp",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_a10",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_alteon",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_array",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cisco_ace",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_f5",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_fortiadc",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_kemp",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_netscaler",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_radware",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_relianoid",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_superiority",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    }
  ],
  "wanopt": [
    {
      "collectType": "snmp_bluecoat",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_exinda",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_riverbed",
      "capabilities": [
        "uptime",
        "cpu",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_venturi",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic"
      ]
    }
  ]
};
