# Generated by Django 4.2.27 on 2026-04-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0047_workflowtaskresult_finished_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="skill_params",
            field=models.JSONField(default=list, verbose_name="技能参数"),
        ),
    ]
