services:
  redis:
    image: redis:5.0.14
    restart: always
    volumes:
      - redis:/data
    command:
      - "redis-server"
      - "--requirepass"
      - "bklite-password"
    ports:
      - "6379:6379"
  nats:
    image: nats:2.10.25
    restart: always
    volumes:
      - ./conf/nats/nats.conf:/etc/nats/nats.conf
      - nats:/nats
    ports:
      - "4222:4222"
      - "7422:7422"
    command:
      - "-c"
      - "/etc/nats/nats.conf"

volumes:
  redis:
  nats:
  # victoria-metrics:
  # postgres:
  # victoria-logs:
  # falkordb:
  # minio:
