# Generated by Django 4.2.27 on 2026-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="ssh_key_passphrase",
            field=models.CharField(blank=True, default="", max_length=256, verbose_name="SSH密钥口令"),
        ),
        migrations.AddField(
            model_name="target",
            name="winrm_transport",
            field=models.CharField(
                choices=[("basic", "Basic"), ("ntlm", "NTLM"), ("kerberos", "Kerberos"), ("credssp", "CredSSP")],
                default="ntlm",
                max_length=32,
                verbose_name="WinRM传输方式",
            ),
        ),
    ]
