# Generated by Django 4.2.7 on 2026-04-20 03:27

import apps.cmdb.models.config_file_version
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_collectmodels_data_cleanup_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectmodels',
            name='task_type',
            field=models.CharField(choices=[('vm', 'VM采集'), ('snmp', 'SNMP采集'), ('k8s', 'K8S采集'), ('cloud', '云采集'), ('protocol', '协议采集'), ('host', '主机采集'), ('db', '数据库采集'), ('middleware', '中间件采集'), ('config_file', '配置文件采集'), ('ip', 'IP采集'), ('other', '其他采集')], help_text='任务类型', max_length=32),
        ),
        migrations.CreateModel(
            name='ConfigFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(help_text='主机实例 ID', max_length=128)),
                ('model_id', models.CharField(help_text='模型 ID', max_length=64)),
                ('version', models.CharField(help_text='版本号（采集时间戳）', max_length=32)),
                ('file_path', models.CharField(help_text='采集时的文件绝对路径', max_length=512)),
                ('file_name', models.CharField(help_text='配置文件名称', max_length=256)),
                ('content_hash', models.CharField(blank=True, default='', help_text='文件内容 SHA256 哈希', max_length=64)),
                ('content', models.FileField(blank=True, help_text='MinIO 中的文本配置文件内容', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='cmdb-config-file'), upload_to=apps.cmdb.models.config_file_version.config_file_upload_to)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='文件大小（字节）')),
                ('status', models.CharField(choices=[('success', '采集成功'), ('file_not_found', '文件不存在'), ('permission_denied', '权限不足'), ('file_too_large', '文件超限'), ('not_text', '非文本文件'), ('error', '采集异常')], help_text='采集结果状态', max_length=32)),
                ('error_message', models.TextField(blank=True, default='', help_text='失败原因描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
                ('collect_task', models.ForeignKey(help_text='关联的采集任务', on_delete=django.db.models.deletion.CASCADE, related_name='config_file_versions', to='cmdb.collectmodels')),
            ],
            options={
                'verbose_name': '配置文件版本',
                'verbose_name_plural': '配置文件版本',
                'ordering': ['-created_at'],
                'index_together': {('instance_id', 'file_path'), ('collect_task_id',)},
            },
        ),
    ]
